Fix query used by check_module_provider_redirect_usage to avoid MySQL/MariaDB errors.
MariaDB in CI tests returned incorrect values.
MySQL locally threw errors:
mysql.connector.errors.ProgrammingError: 1055 (42000): Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'terrareg.analytics.module_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
and
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1055 (42000): Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'terrareg.analytics.module_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
[SQL: SELECT anon_1.analytics_token, anon_1.timestamp
FROM (SELECT max(analytics.id) AS latest_id, analytics.module_name AS module_name, analytics.provider_name AS provider_name, analytics.namespace_name AS namespace_name, analytics.timestamp AS timestamp, analytics.analytics_token AS analytics_token
FROM analytics INNER JOIN module_version ON module_version.id = analytics.parent_module_version INNER JOIN module_provider ON module_version.module_provider_id = module_provider.id
WHERE module_provider.id = %(id_1)s GROUP BY analytics.analytics_token) AS anon_1
WHERE anon_1.module_name = %(module_name_1)s AND anon_1.provider_name = %(provider_name_1)s AND anon_1.namespace_name IN (%(namespace_name_1_1)s) AND anon_1.timestamp >= %(timestamp_1)s]
[parameters: {'id_1': 66, 'module_name_1': 'testredirectdelete', 'provider_name_1': 'testprovider', 'timestamp_1': datetime.datetime(2023, 3, 8, 4, 0), 'namespace_name_1_1': 'testredirect'}]
(Background on this error at: https://sqlalche.me/e/14/f405)

Issue #274