db: Revert Enum type to original version without Postgresql varient
The Postgresql varient caused MySQL migrations to throw the following:
```
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.dialects.mysql.base.MySQLDDLCompiler object at 0x7f47b1a89220> can't render element of type <class 'sqlalchemy.dialects.postgresql.base.CreateEnumType'> (Background on this error at: https://sqlalche.me/e/14/l7de)
```

Issue #562