fix: Fix sql query, where table is being selected, which treats first argument as a where clause, resulting in the column being added to "WHERE" without an operator.
This resulted in:
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) argument of AND must be type boolean, not type character varying
```

Issue #562